### ISSUE TITLE
可以出个python版本的吗

### ISSUE THREAD

**Issue by 2682856025** [TurboHsu/Vocab-Master#1]
楼主大大 没用过go 啥也不懂呀

**Comment by TurboHsu** [comment]
咱还没收工捏 等收工再考虑8

**Comment by longaotian0213** [comment]
安装证书导致Edge浏览器无法使用该如何解决？

**Comment by TurboHsu** [comment]
> 安装证书导致Edge浏览器无法使用该如何解决？

是「NET::ERR_CERT_AUTHORITY_INVALID」？

**Comment by longaotian0213** [comment]
> > 安装证书导致Edge浏览器无法使用该如何解决？
> 
> 是「NET::ERR_CERT_AUTHORITY_INVALID」？

看不懂呀我

**Comment by TurboHsu** [comment]
> > > 安装证书导致Edge浏览器无法使用该如何解决？
> > 
> > 
> > 是「NET::ERR_CERT_AUTHORITY_INVALID」？
> 
> 看不懂呀我

发报错截图，我估计你没把证书扔到「受信任的证书颁发机构」

**Comment by longaotian0213** [comment]
> 

感谢你的回复，已经解决了，虽然这个项目我还是不知道怎么用。怎么打开词达人的班级任务呢？班级任务不支持在电脑上打开，您的描述我这种什么都不知道的小白看不懂呀，可以再详细一点的介绍一下使用方法嘛，非常感谢！

**Comment by TurboHsu** [comment]
> > 
> 
> 感谢你的回复，已经解决了，虽然这个项目我还是不知道怎么用。怎么打开词达人的班级任务呢？班级任务不支持在电脑上打开，您的描述我这种什么都不知道的小白看不懂呀，可以再详细一点的介绍一下使用方法嘛，非常感谢！

微信 for PC -> 词达人 -> 学生端 -> 班级任务

**Comment by longaotian0213** [comment]
非常遗憾，我的词达人只能在手机上做。。。

**Comment by TurboHsu** [comment]
> 非常遗憾，我的词达人只能在手机上做。。。

那这种班级任务我也没见过:(

**Comment by longaotian0213** [comment]
> > 非常遗憾，我的词达人只能在手机上做。。。
> 
> 那这种班级任务我也没见过:(

哈哈，认命了我
