### ISSUE TITLE
部分不能匹配答案

### ISSUE THREAD

**Issue by Winddyyy** [TurboHsu/Vocab-Master#10]
综合教程那本书上的词汇作业不能匹配到答案
![})}ARP~N0P1PNQZ 9M2JS2U](https://user-images.githubusercontent.com/112607991/208600744-768317f6-14c0-4ced-9248-b302126ffa1c.png)

**Comment by Winddyyy** [comment]
![UJWMAA9)_V_N {A5$}}DZ Y](https://user-images.githubusercontent.com/112607991/208601160-9e43f247-300f-4307-9ae3-c74b92638950.png)

**Comment by TurboHsu** [comment]
应该修复了。词达人有个新版的API，输出的JSON和原来的不太一样，可以用版本号区分。请试试看最新的Release。
