### ISSUE TITLE
打开发行包中的vocab-master没有反应

### ISSUE THREAD

**Issue by Raudience** [TurboHsu/Vocab-Master#11]
没有图形化界面，也没有生成cert文件夹，cert文件夹在windows中的生成位置在哪里？

**Comment by TurboHsu** [comment]
请问您正在使用什么操作系统/架构？
证书和字体文件应当存放于 ```%APPDATA%\VocabMaster\``` 下，打开后应该是有GUI的。由于我使用 ```-H windowsgui```参数编译，控制台可能没有输出。

我尝试重新编译了一遍，已经在release中更新了压缩包的内容，请尝试运行```Debug```结尾的可执行文件，该可执行文件没有添加```-H windowsgui```，应当会打开控制台+GUI。请尝试捕捉控制台中的输出。若没有任何输出，您可以尝试自行pull下来编译试试。

以下是我运行该文件的Example。
<img width="861" alt="image" src="https://user-images.githubusercontent.com/47477044/224235963-66b4ad63-6ccc-492b-99b3-bd6d307a3895.png">

**Comment by Raudience** [comment]
现在可以了，打开发行包中的两个可执行程序都有GUI了，谢谢大佬

**Comment by Raudience** [comment]
![image](https://user-images.githubusercontent.com/52769726/224310965-c788310f-6206-41f9-a933-b83783b2c1c1.png)
![image](https://user-images.githubusercontent.com/52769726/224310976-b6096ac4-f1dc-4e1b-95b1-2f6c4664f0a3.png)

还有一个问题就是，老师发布的测试任务在电脑上无法打开怎么办

**Comment by Raudience** [comment]
_大佬貌似要尝试自动化？github上已经有一个cdr开源项目实现很多功能了，例如自动化，只不过因为作者不再维护，而词达人更新了api接口所以才无法使用，或许您可以尝试修复这个项目，或者这个项目中的代码能给您一点帮助
地址：https://github.com/Rain-shadow/cdr

**Comment by TurboHsu** [comment]
抱歉，因为我并没有遇到过测试任务，无法对此进行测试/开发。

测试任务的URL路径或许和学习任务的URL路径不同，不一定奏效。若您愿意尝试，您可以在手机中安装根证书，然后将此程序的Proxy监听到```0.0.0.0```上，使用某些代理软件来代理手机的网络流。这可能需要您拥有对手机的root访问权限。

不过，我认为这是通过一些Header/User-Agent或者其他方式来判断用户是否是使用手机访问的。应该可以实现伪装手机使用。若有空我会尝试实现伪装手机访问。

**Comment by TurboHsu** [comment]
> _大佬貌似要尝试自动化？github上已经有一个cdr开源项目实现很多功能了，例如自动化，只不过因为作者不再维护，而词达人更新了api接口所以才无法使用，或许您可以尝试修复这个项目，或者这个项目中的代码能给您一点帮助 地址：https://github.com/Rain-shadow/cdr

十分感谢提供此信息。目前正在实现该功能。
