### ISSUE TITLE
无法绕过手机端检测

### ISSUE THREAD

**Issue by Sakuravk** [TurboHsu/Vocab-Master#12]
使用后依旧提示手机端登录

**Comment by TurboHsu** [comment]
请尝试清除微信的缓存，JavaScript成功注入后该开关的标签应该会变为Done

**Comment by Sakuravk** [comment]
它一直在等待注入，只成功过几次，请问步骤是:打开软件，打开微信，进入词达人，对吗？

**Comment by Sakuravk** [comment]
谢谢，它只是花费的时间有点长，需要几分钟时间，我误以为失败了

**Comment by TurboHsu** [comment]
这应当是微信内置浏览器缓存的问题，我也不清楚微信浏览器的缓存是如何工作的，其设置中的清除缓存概率性工作（
