### ISSUE TITLE
用不了了，开了软件词达人会白屏

### ISSUE THREAD

**Issue by qxFly** [TurboHsu/Vocab-Master#13]

**Comment by TurboHsu** [comment]
有没有重新选词

**Comment by Sakuravk** [comment]
我也遇到白屏问题了，无法进选词界面

**Comment by TurboHsu** [comment]
> 我也遇到白屏问题了，无法进选词界面

请提供具体的复现流程（例如，在某课程、某任务中一定会触发该问题），以便我测试、修复。如果您乐意的话，麻烦您抓包提供一下问题会发生在哪一个URL上。

**Comment by Sakuravk** [comment]
OK，在勾选js注入后后进入选择测试页面，点击测试后便会白屏，不勾选则正常，我稍后会进行抓包并回复。

**Comment by Sakuravk** [comment]
任何课程都会

**Comment by TurboHsu** [comment]
> OK，在勾选js注入后后进入选择测试页面，点击测试后便会白屏，不勾选则正常，我稍后会进行抓包并回复。

可能是现有的JS注入方案需要修改。我会在近期尝试复现、修复。感谢提交bug

**Comment by qxFly** [comment]
> > 我也遇到白屏问题了，无法进选词界面
> 
> 请提供具体的复现流程（例如，在某课程、某任务中一定会触发该问题），以便我测试、修复。如果您乐意的话，麻烦您抓包提供一下问题会发生在哪一个URL上。

我现在复现不了，不懂为什么突然间又有用了。
我大概描述一下当时的情况，只要打开了软件，重新选完词后词达人就白屏，此时关掉软件，刷新词达人又恢复了显示。或者使用-proxy=false关闭代理后就不会白屏，猜应该是代理方面的问题，当时我一个宿舍都这样。

**Comment by Sakuravk** [comment]
> 

我和你不太一样，我只要不勾选js就没问题，代理也是开的

**Comment by Sakuravk** [comment]
坏了，太奇怪了，这会又和你描述的情况一模一样了，只要打开就会白屏

**Comment by qxFly** [comment]
> 坏了，太奇怪了，这会又和你描述的情况一模一样了，只要打开就会白屏

我现在到不会了

**Comment by Sakuravk** [comment]
> > 坏了，太奇怪了，这又和你描述的情况一样了，只要打开就会白屏
> 
> 我现在到不会了

你能做测试任务吗？

**Comment by qxFly** [comment]
> > > 坏了，太奇怪了，这又和你描述的情况一样了，只要打开就会白屏
> > 
> > 
> > 我现在到不会了
> 
> 你能做测试任务吗？

做不了，提示要手机端

**Comment by TurboHsu** [comment]
> > > > 坏了，太奇怪了，这又和你描述的情况一样了，只要打开就会白屏
> > > 
> > > 
> > > 我现在到不会了
> > 
> > 
> > 你能做测试任务吗？
> 
> 做不了，提示要手机端

那就是没有注入进去。应该是js改版了。

**Comment by TurboHsu** [comment]
我使用同学的账号测试了，是可以使用的。若没有注入成功，请尝试清空微信的缓存，重启微信，应该会好。

至于白屏，你们是否有加载对应的数据？（比如，cet6_hx.json）

**Comment by Sakuravk** [comment]
> 我使用同学的账号测试了，是可以使用的。若没有注入成功，请尝试清空微信的缓存，重启微信，应该会好。
> 
> 至于白屏，你们是否有加载对应的数据？（比如，cet6_hx.json）

我检查了一下我自己抓取的json文件，打开发现是空白的，这应该就是问题。用你提供的cet6是可以的，很谢谢你。再者就是问一下抓不到词怎么办

**Comment by TurboHsu** [comment]
> > 我使用同学的账号测试了，是可以使用的。若没有注入成功，请尝试清空微信的缓存，重启微信，应该会好。
> > 
> > 至于白屏，你们是否有加载对应的数据？（比如，cet6_hx.json）
> 
> 我检查了一下我自己抓取的json文件，打开发现是空白的，这应该就是问题。用你提供的cet6是可以的，很谢谢你。再者就是问一下抓不到词怎么办

你需要知道该课程的一个id，例如cet6_hx。空了我做个地方在程序内展现出来。
