### ISSUE TITLE
新手

### ISSUE THREAD

**Issue by beiluo112233** [TurboHsu/Vocab-Master#14]
新手小白实在看不懂，可以说的具体一点吗？我只能下载那个压缩包下来，剩下的不知道怎么搞了

**Comment by beiluo112233** [comment]
也找不到cert文件夹

**Comment by beiluo112233** [comment]
![633742959474559073](https://github.com/TurboHsu/Vocab-Master/assets/134249524/a1be6928-8ba3-4f97-bdbb-637f2e44f362)

**Comment by beiluo112233** [comment]
这个文件在哪

**Comment by beiluo112233** [comment]
@TurboHsu 作者大大，实在看不懂，为什么没有cert的文件夹

**Comment by TurboHsu** [comment]
请下载Release中已经编译的版本，或者使用您自己的环境编译。cert文件夹会生成在%AppData%中。

**Comment by beiluo112233** [comment]
那个.cer的文件怎么保存到系统的信任根文件中呢，那个信任根文件在哪呢

**Comment by beiluo112233** [comment]
@TurboHsu 我打开也是白屏，我起用了那个js然后没有反应

**Comment by beiluo112233** [comment]
@TurboHsu 怎么加载对应数据呢

**Comment by beiluo112233** [comment]
@TurboHsu 那个数据抓取怎么抓呢，是抓取那个cet6-hx那个json文件吗

**Comment by wuming1235** [comment]
不会不会找不到啊
谁会可以教教马
~~Tip: 帮你把个人信息去除了，我不觉得公布自己的微信号是个安全的做法~~

**Comment by TurboHsu** [comment]
> @TurboHsu 我打开也是白屏，我起用了那个js然后没有反应
> 

若一打开就白屏，同时浏览器打开其他网页提示不安全，请检查证书是否正常导入。若测试任务白屏，目前我只给了六级的词库，可以在data console选中该文件并加载它（~~记得没错的话~~）。

**Comment by beiluo112233** [comment]
@TurboHsu 好的，我已经可以正常运行了，感谢大佬
