### ISSUE TITLE
小白求教

### ISSUE THREAD

**Issue by DE3PDARKFANTASY** [TurboHsu/Vocab-Master#17]
现在一运行这个软件，打开浏览器就提示不安全，微信词达人也白屏，cert文件夹有一个证书，两个.pem后缀的文件，大佬能指导指导我怎么解决这个问题吗

**Comment by DE3PDARKFANTASY** [comment]
TurboHsu commented on Jun 1
@TurboHsu 我打开也是白屏，我起用了那个js然后没有反应

若一打开就白屏，同时浏览器打开其他网页提示不安全，请检查证书是否正常导入。若测试任务白屏，目前我只给了六级的词库，可以在data console选中该文件并加载它（记得没错的话）






之前这条回复我看见了，我也不太清楚证书怎样才是导入成功

**Comment by TurboHsu** [comment]
如果是 `Windows` 系统，你可以打开那个 `cer` 文件，选择`安装证书`，选择`本地计算机`，存储位置选择`受信任的根证书颁发机构`，应该就可以装上了。装上以后你应该就可以在运行此项目的时候正常访问互联网，程序应该会监听词达人相关域名流量并进行处理。

**Comment by DE3PDARKFANTASY** [comment]
谢谢您了，程序已经正常运行了
