### ISSUE TITLE
Adapt self-learning tasks

### ISSUE THREAD

**Issue by TWLW9784** [TurboHsu/Vocab-Master#4]
没接触过什么代理。百度过试了一些方法，但是打开软件还是闪退，而且没有生成任何文件

**Comment by TurboHsu** [comment]
可能解决了，请尝试新的Release，我已经更新了Assets.

**Comment by TWLW9784** [comment]
能够使用了，但是不知道是不是我操作的原因，这些题下方变成只有一个跳过选项，跳过的题全部都0分
![image](https://user-images.githubusercontent.com/101060038/196137126-020ec065-2628-43e0-b407-1e6167e562a9.png)
![image](https://user-images.githubusercontent.com/101060038/196137265-65df3732-5417-4772-adca-e264470098b4.png)

**Comment by TWLW9784** [comment]
还是说本身就是这个效果

**Comment by TurboHsu** [comment]
目前我只做到CET4前几个list，后面可能有其他的题型（TaskID不一样）我没遇到过，所以这个可能是没有适配。

**Comment by TurboHsu** [comment]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/47477044/196137933-db7acbb2-a0ec-436a-a74f-2558a25ec463.png">
目前适配的是这样的效果（

**Comment by TWLW9784** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月17日(星期一) 下午5:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TurboHsu/Vocab-Master] 小白咋使用啊 (Issue #4)






目前我只做到CET4前几个list，后面可能有其他的题型（TaskID不一样）我没遇到过，所以这个可能是没有适配。

**Comment by TurboHsu** [comment]
后续我遇到新题型会更新这个项目，目前我也没法做其他的

**Comment by TWLW9784** [comment]
支持




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月17日(星期一) 下午5:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TurboHsu/Vocab-Master] 小白咋使用啊 (Issue #4)





 
Closed #4 as completed.

**Comment by TurboHsu** [comment]
我稍微研究了下 你这貌似是自学任务？

**Comment by TWLW9784** [comment]
对，我这个号暂时没有班级任务，有了我在测试一下，到时候反馈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月17日(星期一) 下午5:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TurboHsu/Vocab-Master] 小白咋使用啊 (Issue #4)





 
我稍微研究了下 你这貌似是自学任务？

**Comment by TurboHsu** [comment]
ok 我这几天有空也把自学任务适配一下 感谢支持

**Comment by TWLW9784** [comment]
还是0分,有办法解决嘛?

**Comment by TurboHsu** [comment]
> 还是0分,有办法解决嘛?

适配自学任务似乎需要重新分析流程，这有点麻烦，目前开发阶段只考虑对课堂任务的适配。 感谢支持。

**Comment by TurboHsu** [comment]
大概支持了，请检查最新的Release。
