### ISSUE TITLE
对Mac系统不友好

### ISSUE THREAD

**Issue by 2682856025** [TurboHsu/Vocab-Master#5]
Mac系统没法使用呀

**Comment by TurboHsu** [comment]
mac自行编译 有log请贴log

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: 不知名的虫子 ***@***.***>
Sent: Sunday, October 23, 2022 12:09:15 AM
To: TurboHsu/Vocab-Master ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TurboHsu/Vocab-Master] 对Mac系统不友好 (Issue #5)


Mac系统没法使用呀

―

**Comment by TurboHsu** [comment]
如果有具体问题，请带上日志/截图重新开启此issue。

**Comment by zhufucdev** [comment]
请看release
